; Song Untitled, in AKY version 1.1, generated by Arkos Tracker 3.

Vaches_Subsong0
Vaches_Subsong0DisarkGenerateExternalLabel

; Header
Vaches_Subsong0DisarkByteRegionStart0
    db 128    ; Format version: 0 and endianness: little-endian.
    db 3    ; How many channels are encoded.
; Frequency of the PSG index 0: 1500000Hz.
    db 96
    db 227
    db 22
    db 0
Vaches_Subsong0DisarkByteRegionEnd0

Vaches_Subsong0_Linker
Vaches_Subsong0DisarkPointerRegionStart1
; Position 0
Vaches_Subsong0_LinkerLoop
; Loops here.
Vaches_Subsong0DisarkWordForceNonReference2
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_6
    dw Vaches_Subsong0_Track_4
    dw Vaches_Subsong0_Track_8

; Position 1
Vaches_Subsong0DisarkWordForceNonReference3
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_6
    dw Vaches_Subsong0_Track_4
    dw Vaches_Subsong0_Track_8

; Position 2
Vaches_Subsong0DisarkWordForceNonReference4
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_6
    dw Vaches_Subsong0_Track_7
    dw Vaches_Subsong0_Track_8

; Position 3
Vaches_Subsong0DisarkWordForceNonReference5
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_9
    dw Vaches_Subsong0_Track_10
    dw Vaches_Subsong0_Track_11

; Position 4
Vaches_Subsong0DisarkWordForceNonReference6
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_59
    dw Vaches_Subsong0_Track_13
    dw Vaches_Subsong0_Track_59

; Position 5
Vaches_Subsong0DisarkWordForceNonReference7
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_18
    dw Vaches_Subsong0_Track_22
    dw Vaches_Subsong0_Track_23

; Position 6
Vaches_Subsong0DisarkWordForceNonReference8
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_18
    dw Vaches_Subsong0_Track_22
    dw Vaches_Subsong0_Track_23

; Position 7
Vaches_Subsong0DisarkWordForceNonReference9
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_21
    dw Vaches_Subsong0_Track_22
    dw Vaches_Subsong0_Track_23

; Position 8
Vaches_Subsong0DisarkWordForceNonReference10
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_24
    dw Vaches_Subsong0_Track_49
    dw Vaches_Subsong0_Track_50

; Position 9
Vaches_Subsong0DisarkWordForceNonReference11
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_27
    dw Vaches_Subsong0_Track_59
    dw Vaches_Subsong0_Track_59

; Position 10
Vaches_Subsong0DisarkWordForceNonReference12
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_46
    dw Vaches_Subsong0_Track_31
    dw Vaches_Subsong0_Track_47

; Position 11
Vaches_Subsong0DisarkWordForceNonReference13
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_47
    dw Vaches_Subsong0_Track_34
    dw Vaches_Subsong0_Track_50

; Position 12
Vaches_Subsong0DisarkWordForceNonReference14
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_52
    dw Vaches_Subsong0_Track_37
    dw Vaches_Subsong0_Track_53

; Position 13
Vaches_Subsong0DisarkWordForceNonReference15
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_55
    dw Vaches_Subsong0_Track_40
    dw Vaches_Subsong0_Track_56

; Position 14
Vaches_Subsong0DisarkWordForceNonReference16
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_59
    dw Vaches_Subsong0_Track_43
    dw Vaches_Subsong0_Track_59

; Position 15
Vaches_Subsong0DisarkWordForceNonReference17
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_45
    dw Vaches_Subsong0_Track_46
    dw Vaches_Subsong0_Track_47

; Position 16
Vaches_Subsong0DisarkWordForceNonReference18
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_48
    dw Vaches_Subsong0_Track_49
    dw Vaches_Subsong0_Track_50

; Position 17
Vaches_Subsong0DisarkWordForceNonReference19
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_51
    dw Vaches_Subsong0_Track_52
    dw Vaches_Subsong0_Track_53

; Position 18
Vaches_Subsong0DisarkWordForceNonReference20
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_54
    dw Vaches_Subsong0_Track_55
    dw Vaches_Subsong0_Track_56

; Position 19
Vaches_Subsong0DisarkWordForceNonReference21
    dw 144    ; Duration in frames.
    dw Vaches_Subsong0_Track_57
    dw Vaches_Subsong0_Track_59
    dw Vaches_Subsong0_Track_59

Vaches_Subsong0DisarkWordForceNonReference22
    dw 0    ; Loops (duration = 0).
    dw Vaches_Subsong0_LinkerLoop
Vaches_Subsong0DisarkPointerRegionEnd1

; The tracks.
Vaches_Subsong0_Track_4
Vaches_Subsong0DisarkByteRegionStart23
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd23
Vaches_Subsong0DisarkPointerRegionStart24
    dw Vaches_Subsong0_RegisterBlock_0
Vaches_Subsong0DisarkPointerRegionEnd24

Vaches_Subsong0DisarkByteRegionStart25
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd25
Vaches_Subsong0DisarkPointerRegionStart26
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd26

Vaches_Subsong0DisarkByteRegionStart27
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd27
Vaches_Subsong0DisarkPointerRegionStart28
    dw Vaches_Subsong0_RegisterBlock_2
Vaches_Subsong0DisarkPointerRegionEnd28

Vaches_Subsong0DisarkByteRegionStart29
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd29
Vaches_Subsong0DisarkPointerRegionStart30
    dw Vaches_Subsong0_RegisterBlock_0
Vaches_Subsong0DisarkPointerRegionEnd30

Vaches_Subsong0DisarkByteRegionStart31
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd31
Vaches_Subsong0DisarkPointerRegionStart32
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd32

Vaches_Subsong0DisarkByteRegionStart33
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd33
Vaches_Subsong0DisarkPointerRegionStart34
    dw Vaches_Subsong0_RegisterBlock_2
Vaches_Subsong0DisarkPointerRegionEnd34

Vaches_Subsong0_Track_6
Vaches_Subsong0DisarkByteRegionStart35
    db 3    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd35
Vaches_Subsong0DisarkPointerRegionStart36
    dw Vaches_Subsong0_RegisterBlock_6
Vaches_Subsong0DisarkPointerRegionEnd36

Vaches_Subsong0DisarkByteRegionStart37
    db 141    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd37
Vaches_Subsong0DisarkPointerRegionStart38
    dw Vaches_Subsong0_RegisterBlock_7
Vaches_Subsong0DisarkPointerRegionEnd38

Vaches_Subsong0_Track_7
Vaches_Subsong0DisarkByteRegionStart39
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd39
Vaches_Subsong0DisarkPointerRegionStart40
    dw Vaches_Subsong0_RegisterBlock_0
Vaches_Subsong0DisarkPointerRegionEnd40

Vaches_Subsong0DisarkByteRegionStart41
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd41
Vaches_Subsong0DisarkPointerRegionStart42
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd42

Vaches_Subsong0DisarkByteRegionStart43
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd43
Vaches_Subsong0DisarkPointerRegionStart44
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd44

Vaches_Subsong0DisarkByteRegionStart45
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd45
Vaches_Subsong0DisarkPointerRegionStart46
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd46

Vaches_Subsong0DisarkByteRegionStart47
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd47
Vaches_Subsong0DisarkPointerRegionStart48
    dw Vaches_Subsong0_RegisterBlock_2
Vaches_Subsong0DisarkPointerRegionEnd48

Vaches_Subsong0DisarkByteRegionStart49
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd49
Vaches_Subsong0DisarkPointerRegionStart50
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd50

Vaches_Subsong0_Track_8
Vaches_Subsong0DisarkByteRegionStart51
    db 3    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd51
Vaches_Subsong0DisarkPointerRegionStart52
    dw Vaches_Subsong0_RegisterBlock_14
Vaches_Subsong0DisarkPointerRegionEnd52

Vaches_Subsong0DisarkByteRegionStart53
    db 141    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd53
Vaches_Subsong0DisarkPointerRegionStart54
    dw Vaches_Subsong0_RegisterBlock_15
Vaches_Subsong0DisarkPointerRegionEnd54

Vaches_Subsong0_Track_9
Vaches_Subsong0DisarkByteRegionStart55
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd55
Vaches_Subsong0DisarkPointerRegionStart56
    dw Vaches_Subsong0_RegisterBlock_16
Vaches_Subsong0DisarkPointerRegionEnd56

Vaches_Subsong0_Track_10
Vaches_Subsong0DisarkByteRegionStart57
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd57
Vaches_Subsong0DisarkPointerRegionStart58
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd58

Vaches_Subsong0DisarkByteRegionStart59
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd59
Vaches_Subsong0DisarkPointerRegionStart60
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd60

Vaches_Subsong0DisarkByteRegionStart61
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd61
Vaches_Subsong0DisarkPointerRegionStart62
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd62

Vaches_Subsong0DisarkByteRegionStart63
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd63
Vaches_Subsong0DisarkPointerRegionStart64
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd64

Vaches_Subsong0DisarkByteRegionStart65
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd65
Vaches_Subsong0DisarkPointerRegionStart66
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd66

Vaches_Subsong0DisarkByteRegionStart67
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd67
Vaches_Subsong0DisarkPointerRegionStart68
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd68

Vaches_Subsong0DisarkByteRegionStart69
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd69
Vaches_Subsong0DisarkPointerRegionStart70
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd70

Vaches_Subsong0DisarkByteRegionStart71
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd71
Vaches_Subsong0DisarkPointerRegionStart72
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd72

Vaches_Subsong0DisarkByteRegionStart73
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd73
Vaches_Subsong0DisarkPointerRegionStart74
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd74

Vaches_Subsong0DisarkByteRegionStart75
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd75
Vaches_Subsong0DisarkPointerRegionStart76
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd76

Vaches_Subsong0DisarkByteRegionStart77
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd77
Vaches_Subsong0DisarkPointerRegionStart78
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd78

Vaches_Subsong0DisarkByteRegionStart79
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd79
Vaches_Subsong0DisarkPointerRegionStart80
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd80

Vaches_Subsong0DisarkByteRegionStart81
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd81
Vaches_Subsong0DisarkPointerRegionStart82
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd82

Vaches_Subsong0DisarkByteRegionStart83
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd83
Vaches_Subsong0DisarkPointerRegionStart84
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd84

Vaches_Subsong0DisarkByteRegionStart85
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd85
Vaches_Subsong0DisarkPointerRegionStart86
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd86

Vaches_Subsong0DisarkByteRegionStart87
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd87
Vaches_Subsong0DisarkPointerRegionStart88
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd88

Vaches_Subsong0DisarkByteRegionStart89
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd89
Vaches_Subsong0DisarkPointerRegionStart90
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd90

Vaches_Subsong0DisarkByteRegionStart91
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd91
Vaches_Subsong0DisarkPointerRegionStart92
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd92

Vaches_Subsong0DisarkByteRegionStart93
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd93
Vaches_Subsong0DisarkPointerRegionStart94
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd94

Vaches_Subsong0DisarkByteRegionStart95
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd95
Vaches_Subsong0DisarkPointerRegionStart96
    dw Vaches_Subsong0_RegisterBlock_36
Vaches_Subsong0DisarkPointerRegionEnd96

Vaches_Subsong0DisarkByteRegionStart97
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd97
Vaches_Subsong0DisarkPointerRegionStart98
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd98

Vaches_Subsong0_Track_11
Vaches_Subsong0DisarkByteRegionStart99
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd99
Vaches_Subsong0DisarkPointerRegionStart100
    dw Vaches_Subsong0_RegisterBlock_38
Vaches_Subsong0DisarkPointerRegionEnd100

Vaches_Subsong0_Track_13
Vaches_Subsong0DisarkByteRegionStart101
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd101
Vaches_Subsong0DisarkPointerRegionStart102
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd102

Vaches_Subsong0_Track_18
Vaches_Subsong0DisarkByteRegionStart103
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd103
Vaches_Subsong0DisarkPointerRegionStart104
    dw Vaches_Subsong0_RegisterBlock_117
Vaches_Subsong0DisarkPointerRegionEnd104

Vaches_Subsong0DisarkByteRegionStart105
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd105
Vaches_Subsong0DisarkPointerRegionStart106
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd106

Vaches_Subsong0DisarkByteRegionStart107
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd107
Vaches_Subsong0DisarkPointerRegionStart108
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd108

Vaches_Subsong0DisarkByteRegionStart109
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd109
Vaches_Subsong0DisarkPointerRegionStart110
    dw Vaches_Subsong0_RegisterBlock_117
Vaches_Subsong0DisarkPointerRegionEnd110

Vaches_Subsong0DisarkByteRegionStart111
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd111
Vaches_Subsong0DisarkPointerRegionStart112
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd112

Vaches_Subsong0DisarkByteRegionStart113
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd113
Vaches_Subsong0DisarkPointerRegionStart114
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd114

Vaches_Subsong0_Track_21
Vaches_Subsong0DisarkByteRegionStart115
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd115
Vaches_Subsong0DisarkPointerRegionStart116
    dw Vaches_Subsong0_RegisterBlock_117
Vaches_Subsong0DisarkPointerRegionEnd116

Vaches_Subsong0DisarkByteRegionStart117
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd117
Vaches_Subsong0DisarkPointerRegionStart118
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd118

Vaches_Subsong0DisarkByteRegionStart119
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd119
Vaches_Subsong0DisarkPointerRegionStart120
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd120

Vaches_Subsong0DisarkByteRegionStart121
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd121
Vaches_Subsong0DisarkPointerRegionStart122
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd122

Vaches_Subsong0DisarkByteRegionStart123
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd123
Vaches_Subsong0DisarkPointerRegionStart124
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd124

Vaches_Subsong0DisarkByteRegionStart125
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd125
Vaches_Subsong0DisarkPointerRegionStart126
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd126

Vaches_Subsong0_Track_22
Vaches_Subsong0DisarkByteRegionStart127
    db 3    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd127
Vaches_Subsong0DisarkPointerRegionStart128
    dw Vaches_Subsong0_RegisterBlock_52
Vaches_Subsong0DisarkPointerRegionEnd128

Vaches_Subsong0DisarkByteRegionStart129
    db 141    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd129
Vaches_Subsong0DisarkPointerRegionStart130
    dw Vaches_Subsong0_RegisterBlock_165
Vaches_Subsong0DisarkPointerRegionEnd130

Vaches_Subsong0_Track_23
Vaches_Subsong0DisarkByteRegionStart131
    db 3    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd131
Vaches_Subsong0DisarkPointerRegionStart132
    dw Vaches_Subsong0_RegisterBlock_54
Vaches_Subsong0DisarkPointerRegionEnd132

Vaches_Subsong0DisarkByteRegionStart133
    db 141    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd133
Vaches_Subsong0DisarkPointerRegionStart134
    dw Vaches_Subsong0_RegisterBlock_166
Vaches_Subsong0DisarkPointerRegionEnd134

Vaches_Subsong0_Track_24
Vaches_Subsong0DisarkByteRegionStart135
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd135
Vaches_Subsong0DisarkPointerRegionStart136
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd136

Vaches_Subsong0DisarkByteRegionStart137
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd137
Vaches_Subsong0DisarkPointerRegionStart138
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd138

Vaches_Subsong0DisarkByteRegionStart139
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd139
Vaches_Subsong0DisarkPointerRegionStart140
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd140

Vaches_Subsong0DisarkByteRegionStart141
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd141
Vaches_Subsong0DisarkPointerRegionStart142
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd142

Vaches_Subsong0DisarkByteRegionStart143
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd143
Vaches_Subsong0DisarkPointerRegionStart144
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd144

Vaches_Subsong0DisarkByteRegionStart145
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd145
Vaches_Subsong0DisarkPointerRegionStart146
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd146

Vaches_Subsong0DisarkByteRegionStart147
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd147
Vaches_Subsong0DisarkPointerRegionStart148
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd148

Vaches_Subsong0DisarkByteRegionStart149
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd149
Vaches_Subsong0DisarkPointerRegionStart150
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd150

Vaches_Subsong0DisarkByteRegionStart151
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd151
Vaches_Subsong0DisarkPointerRegionStart152
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd152

Vaches_Subsong0DisarkByteRegionStart153
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd153
Vaches_Subsong0DisarkPointerRegionStart154
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd154

Vaches_Subsong0DisarkByteRegionStart155
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd155
Vaches_Subsong0DisarkPointerRegionStart156
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd156

Vaches_Subsong0DisarkByteRegionStart157
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd157
Vaches_Subsong0DisarkPointerRegionStart158
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd158

Vaches_Subsong0DisarkByteRegionStart159
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd159
Vaches_Subsong0DisarkPointerRegionStart160
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd160

Vaches_Subsong0DisarkByteRegionStart161
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd161
Vaches_Subsong0DisarkPointerRegionStart162
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd162

Vaches_Subsong0DisarkByteRegionStart163
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd163
Vaches_Subsong0DisarkPointerRegionStart164
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd164

Vaches_Subsong0DisarkByteRegionStart165
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd165
Vaches_Subsong0DisarkPointerRegionStart166
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd166

Vaches_Subsong0DisarkByteRegionStart167
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd167
Vaches_Subsong0DisarkPointerRegionStart168
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd168

Vaches_Subsong0DisarkByteRegionStart169
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd169
Vaches_Subsong0DisarkPointerRegionStart170
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd170

Vaches_Subsong0DisarkByteRegionStart171
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd171
Vaches_Subsong0DisarkPointerRegionStart172
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd172

Vaches_Subsong0DisarkByteRegionStart173
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd173
Vaches_Subsong0DisarkPointerRegionStart174
    dw Vaches_Subsong0_RegisterBlock_75
Vaches_Subsong0DisarkPointerRegionEnd174

Vaches_Subsong0DisarkByteRegionStart175
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd175
Vaches_Subsong0DisarkPointerRegionStart176
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd176

Vaches_Subsong0_Track_27
Vaches_Subsong0DisarkByteRegionStart177
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd177
Vaches_Subsong0DisarkPointerRegionStart178
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd178

Vaches_Subsong0_Track_31
Vaches_Subsong0DisarkByteRegionStart179
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd179
Vaches_Subsong0DisarkPointerRegionStart180
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd180

Vaches_Subsong0DisarkByteRegionStart181
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd181
Vaches_Subsong0DisarkPointerRegionStart182
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd182

Vaches_Subsong0DisarkByteRegionStart183
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd183
Vaches_Subsong0DisarkPointerRegionStart184
    dw Vaches_Subsong0_RegisterBlock_80
Vaches_Subsong0DisarkPointerRegionEnd184

Vaches_Subsong0DisarkByteRegionStart185
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd185
Vaches_Subsong0DisarkPointerRegionStart186
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd186

Vaches_Subsong0DisarkByteRegionStart187
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd187
Vaches_Subsong0DisarkPointerRegionStart188
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd188

Vaches_Subsong0DisarkByteRegionStart189
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd189
Vaches_Subsong0DisarkPointerRegionStart190
    dw Vaches_Subsong0_RegisterBlock_80
Vaches_Subsong0DisarkPointerRegionEnd190

Vaches_Subsong0_Track_34
Vaches_Subsong0DisarkByteRegionStart191
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd191
Vaches_Subsong0DisarkPointerRegionStart192
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd192

Vaches_Subsong0DisarkByteRegionStart193
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd193
Vaches_Subsong0DisarkPointerRegionStart194
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd194

Vaches_Subsong0DisarkByteRegionStart195
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd195
Vaches_Subsong0DisarkPointerRegionStart196
    dw Vaches_Subsong0_RegisterBlock_80
Vaches_Subsong0DisarkPointerRegionEnd196

Vaches_Subsong0DisarkByteRegionStart197
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd197
Vaches_Subsong0DisarkPointerRegionStart198
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd198

Vaches_Subsong0DisarkByteRegionStart199
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd199
Vaches_Subsong0DisarkPointerRegionStart200
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd200

Vaches_Subsong0DisarkByteRegionStart201
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd201
Vaches_Subsong0DisarkPointerRegionStart202
    dw Vaches_Subsong0_RegisterBlock_2
Vaches_Subsong0DisarkPointerRegionEnd202

Vaches_Subsong0_Track_37
Vaches_Subsong0DisarkByteRegionStart203
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd203
Vaches_Subsong0DisarkPointerRegionStart204
    dw Vaches_Subsong0_RegisterBlock_0
Vaches_Subsong0DisarkPointerRegionEnd204

Vaches_Subsong0DisarkByteRegionStart205
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd205
Vaches_Subsong0DisarkPointerRegionStart206
    dw Vaches_Subsong0_RegisterBlock_78
Vaches_Subsong0DisarkPointerRegionEnd206

Vaches_Subsong0DisarkByteRegionStart207
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd207
Vaches_Subsong0DisarkPointerRegionStart208
    dw Vaches_Subsong0_RegisterBlock_13
Vaches_Subsong0DisarkPointerRegionEnd208

Vaches_Subsong0DisarkByteRegionStart209
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd209
Vaches_Subsong0DisarkPointerRegionStart210
    dw Vaches_Subsong0_RegisterBlock_93
Vaches_Subsong0DisarkPointerRegionEnd210

Vaches_Subsong0DisarkByteRegionStart211
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd211
Vaches_Subsong0DisarkPointerRegionStart212
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd212

Vaches_Subsong0DisarkByteRegionStart213
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd213
Vaches_Subsong0DisarkPointerRegionStart214
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd214

Vaches_Subsong0_Track_40
Vaches_Subsong0DisarkByteRegionStart215
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd215
Vaches_Subsong0DisarkPointerRegionStart216
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd216

Vaches_Subsong0DisarkByteRegionStart217
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd217
Vaches_Subsong0DisarkPointerRegionStart218
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd218

Vaches_Subsong0DisarkByteRegionStart219
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd219
Vaches_Subsong0DisarkPointerRegionStart220
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd220

Vaches_Subsong0DisarkByteRegionStart221
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd221
Vaches_Subsong0DisarkPointerRegionStart222
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd222

Vaches_Subsong0DisarkByteRegionStart223
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd223
Vaches_Subsong0DisarkPointerRegionStart224
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd224

Vaches_Subsong0DisarkByteRegionStart225
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd225
Vaches_Subsong0DisarkPointerRegionStart226
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd226

Vaches_Subsong0DisarkByteRegionStart227
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd227
Vaches_Subsong0DisarkPointerRegionStart228
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd228

Vaches_Subsong0DisarkByteRegionStart229
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd229
Vaches_Subsong0DisarkPointerRegionStart230
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd230

Vaches_Subsong0DisarkByteRegionStart231
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd231
Vaches_Subsong0DisarkPointerRegionStart232
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd232

Vaches_Subsong0DisarkByteRegionStart233
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd233
Vaches_Subsong0DisarkPointerRegionStart234
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd234

Vaches_Subsong0DisarkByteRegionStart235
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd235
Vaches_Subsong0DisarkPointerRegionStart236
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd236

Vaches_Subsong0DisarkByteRegionStart237
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd237
Vaches_Subsong0DisarkPointerRegionStart238
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd238

Vaches_Subsong0DisarkByteRegionStart239
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd239
Vaches_Subsong0DisarkPointerRegionStart240
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd240

Vaches_Subsong0DisarkByteRegionStart241
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd241
Vaches_Subsong0DisarkPointerRegionStart242
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd242

Vaches_Subsong0DisarkByteRegionStart243
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd243
Vaches_Subsong0DisarkPointerRegionStart244
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd244

Vaches_Subsong0DisarkByteRegionStart245
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd245
Vaches_Subsong0DisarkPointerRegionStart246
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd246

Vaches_Subsong0DisarkByteRegionStart247
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd247
Vaches_Subsong0DisarkPointerRegionStart248
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd248

Vaches_Subsong0DisarkByteRegionStart249
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd249
Vaches_Subsong0DisarkPointerRegionStart250
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd250

Vaches_Subsong0DisarkByteRegionStart251
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd251
Vaches_Subsong0DisarkPointerRegionStart252
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd252

Vaches_Subsong0DisarkByteRegionStart253
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd253
Vaches_Subsong0DisarkPointerRegionStart254
    dw Vaches_Subsong0_RegisterBlock_93
Vaches_Subsong0DisarkPointerRegionEnd254

Vaches_Subsong0DisarkByteRegionStart255
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd255
Vaches_Subsong0DisarkPointerRegionStart256
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd256

Vaches_Subsong0_Track_43
Vaches_Subsong0DisarkByteRegionStart257
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd257
Vaches_Subsong0DisarkPointerRegionStart258
    dw Vaches_Subsong0_RegisterBlock_117
Vaches_Subsong0DisarkPointerRegionEnd258

Vaches_Subsong0_Track_45
Vaches_Subsong0DisarkByteRegionStart259
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd259
Vaches_Subsong0DisarkPointerRegionStart260
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd260

Vaches_Subsong0DisarkByteRegionStart261
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd261
Vaches_Subsong0DisarkPointerRegionStart262
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd262

Vaches_Subsong0DisarkByteRegionStart263
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd263
Vaches_Subsong0DisarkPointerRegionStart264
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd264

Vaches_Subsong0DisarkByteRegionStart265
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd265
Vaches_Subsong0DisarkPointerRegionStart266
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd266

Vaches_Subsong0DisarkByteRegionStart267
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd267
Vaches_Subsong0DisarkPointerRegionStart268
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd268

Vaches_Subsong0DisarkByteRegionStart269
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd269
Vaches_Subsong0DisarkPointerRegionStart270
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd270

Vaches_Subsong0_Track_46
Vaches_Subsong0DisarkByteRegionStart271
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd271
Vaches_Subsong0DisarkPointerRegionStart272
    dw Vaches_Subsong0_RegisterBlock_124
Vaches_Subsong0DisarkPointerRegionEnd272

Vaches_Subsong0_Track_47
Vaches_Subsong0DisarkByteRegionStart273
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd273
Vaches_Subsong0DisarkPointerRegionStart274
    dw Vaches_Subsong0_RegisterBlock_125
Vaches_Subsong0DisarkPointerRegionEnd274

Vaches_Subsong0_Track_48
Vaches_Subsong0DisarkByteRegionStart275
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd275
Vaches_Subsong0DisarkPointerRegionStart276
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd276

Vaches_Subsong0DisarkByteRegionStart277
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd277
Vaches_Subsong0DisarkPointerRegionStart278
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd278

Vaches_Subsong0DisarkByteRegionStart279
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd279
Vaches_Subsong0DisarkPointerRegionStart280
    dw Vaches_Subsong0_RegisterBlock_10
Vaches_Subsong0DisarkPointerRegionEnd280

Vaches_Subsong0DisarkByteRegionStart281
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd281
Vaches_Subsong0DisarkPointerRegionStart282
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd282

Vaches_Subsong0DisarkByteRegionStart283
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd283
Vaches_Subsong0DisarkPointerRegionStart284
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd284

Vaches_Subsong0DisarkByteRegionStart285
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd285
Vaches_Subsong0DisarkPointerRegionStart286
    dw Vaches_Subsong0_RegisterBlock_39
Vaches_Subsong0DisarkPointerRegionEnd286

Vaches_Subsong0_Track_49
Vaches_Subsong0DisarkByteRegionStart287
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd287
Vaches_Subsong0DisarkPointerRegionStart288
    dw Vaches_Subsong0_RegisterBlock_16
Vaches_Subsong0DisarkPointerRegionEnd288

Vaches_Subsong0_Track_50
Vaches_Subsong0DisarkByteRegionStart289
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd289
Vaches_Subsong0DisarkPointerRegionStart290
    dw Vaches_Subsong0_RegisterBlock_133
Vaches_Subsong0DisarkPointerRegionEnd290

Vaches_Subsong0_Track_51
Vaches_Subsong0DisarkByteRegionStart291
    db 63    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd291
Vaches_Subsong0DisarkPointerRegionStart292
    dw Vaches_Subsong0_RegisterBlock_117
Vaches_Subsong0DisarkPointerRegionEnd292

Vaches_Subsong0DisarkByteRegionStart293
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd293
Vaches_Subsong0DisarkPointerRegionStart294
    dw Vaches_Subsong0_RegisterBlock_118
Vaches_Subsong0DisarkPointerRegionEnd294

Vaches_Subsong0DisarkByteRegionStart295
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd295
Vaches_Subsong0DisarkPointerRegionStart296
    dw Vaches_Subsong0_RegisterBlock_51
Vaches_Subsong0DisarkPointerRegionEnd296

Vaches_Subsong0DisarkByteRegionStart297
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd297
Vaches_Subsong0DisarkPointerRegionStart298
    dw Vaches_Subsong0_RegisterBlock_137
Vaches_Subsong0DisarkPointerRegionEnd298

Vaches_Subsong0DisarkByteRegionStart299
    db 15    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd299
Vaches_Subsong0DisarkPointerRegionStart300
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd300

Vaches_Subsong0DisarkByteRegionStart301
    db 18    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd301
Vaches_Subsong0DisarkPointerRegionStart302
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd302

Vaches_Subsong0_Track_52
Vaches_Subsong0DisarkByteRegionStart303
    db 96    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd303
Vaches_Subsong0DisarkPointerRegionStart304
    dw Vaches_Subsong0_RegisterBlock_165
Vaches_Subsong0DisarkPointerRegionEnd304

Vaches_Subsong0DisarkByteRegionStart305
    db 48    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd305
Vaches_Subsong0DisarkPointerRegionStart306
    dw Vaches_Subsong0_RegisterBlock_141
Vaches_Subsong0DisarkPointerRegionEnd306

Vaches_Subsong0_Track_53
Vaches_Subsong0DisarkByteRegionStart307
    db 96    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd307
Vaches_Subsong0DisarkPointerRegionStart308
    dw Vaches_Subsong0_RegisterBlock_166
Vaches_Subsong0DisarkPointerRegionEnd308

Vaches_Subsong0DisarkByteRegionStart309
    db 48    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd309
Vaches_Subsong0DisarkPointerRegionStart310
    dw Vaches_Subsong0_RegisterBlock_143
Vaches_Subsong0DisarkPointerRegionEnd310

Vaches_Subsong0_Track_54
Vaches_Subsong0DisarkByteRegionStart311
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd311
Vaches_Subsong0DisarkPointerRegionStart312
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd312

Vaches_Subsong0DisarkByteRegionStart313
    db 9    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd313
Vaches_Subsong0DisarkPointerRegionStart314
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd314

Vaches_Subsong0DisarkByteRegionStart315
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd315
Vaches_Subsong0DisarkPointerRegionStart316
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd316

Vaches_Subsong0DisarkByteRegionStart317
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd317
Vaches_Subsong0DisarkPointerRegionStart318
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd318

Vaches_Subsong0DisarkByteRegionStart319
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd319
Vaches_Subsong0DisarkPointerRegionStart320
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd320

Vaches_Subsong0DisarkByteRegionStart321
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd321
Vaches_Subsong0DisarkPointerRegionStart322
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd322

Vaches_Subsong0DisarkByteRegionStart323
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd323
Vaches_Subsong0DisarkPointerRegionStart324
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd324

Vaches_Subsong0DisarkByteRegionStart325
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd325
Vaches_Subsong0DisarkPointerRegionStart326
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd326

Vaches_Subsong0DisarkByteRegionStart327
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd327
Vaches_Subsong0DisarkPointerRegionStart328
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd328

Vaches_Subsong0DisarkByteRegionStart329
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd329
Vaches_Subsong0DisarkPointerRegionStart330
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd330

Vaches_Subsong0DisarkByteRegionStart331
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd331
Vaches_Subsong0DisarkPointerRegionStart332
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd332

Vaches_Subsong0DisarkByteRegionStart333
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd333
Vaches_Subsong0DisarkPointerRegionStart334
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd334

Vaches_Subsong0DisarkByteRegionStart335
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd335
Vaches_Subsong0DisarkPointerRegionStart336
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd336

Vaches_Subsong0DisarkByteRegionStart337
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd337
Vaches_Subsong0DisarkPointerRegionStart338
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd338

Vaches_Subsong0DisarkByteRegionStart339
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd339
Vaches_Subsong0DisarkPointerRegionStart340
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd340

Vaches_Subsong0DisarkByteRegionStart341
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd341
Vaches_Subsong0DisarkPointerRegionStart342
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd342

Vaches_Subsong0DisarkByteRegionStart343
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd343
Vaches_Subsong0DisarkPointerRegionStart344
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd344

Vaches_Subsong0DisarkByteRegionStart345
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd345
Vaches_Subsong0DisarkPointerRegionStart346
    dw Vaches_Subsong0_RegisterBlock_48
Vaches_Subsong0DisarkPointerRegionEnd346

Vaches_Subsong0DisarkByteRegionStart347
    db 6    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd347
Vaches_Subsong0DisarkPointerRegionStart348
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd348

Vaches_Subsong0DisarkByteRegionStart349
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd349
Vaches_Subsong0DisarkPointerRegionStart350
    dw Vaches_Subsong0_RegisterBlock_137
Vaches_Subsong0DisarkPointerRegionEnd350

Vaches_Subsong0DisarkByteRegionStart351
    db 12    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd351
Vaches_Subsong0DisarkPointerRegionStart352
    dw Vaches_Subsong0_RegisterBlock_77
Vaches_Subsong0DisarkPointerRegionEnd352

Vaches_Subsong0_Track_55
Vaches_Subsong0DisarkByteRegionStart353
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd353
Vaches_Subsong0DisarkPointerRegionStart354
    dw Vaches_Subsong0_RegisterBlock_165
Vaches_Subsong0DisarkPointerRegionEnd354

Vaches_Subsong0_Track_56
Vaches_Subsong0DisarkByteRegionStart355
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd355
Vaches_Subsong0DisarkPointerRegionStart356
    dw Vaches_Subsong0_RegisterBlock_166
Vaches_Subsong0DisarkPointerRegionEnd356

Vaches_Subsong0_Track_57
Vaches_Subsong0DisarkByteRegionStart357
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd357
Vaches_Subsong0DisarkPointerRegionStart358
    dw Vaches_Subsong0_RegisterBlock_167
Vaches_Subsong0DisarkPointerRegionEnd358

Vaches_Subsong0_Track_59
Vaches_Subsong0DisarkByteRegionStart359
    db 144    ; Duration.
Vaches_Subsong0DisarkByteRegionEnd359
Vaches_Subsong0DisarkPointerRegionStart360
    dw Vaches_Subsong0_RegisterBlock_168
Vaches_Subsong0DisarkPointerRegionEnd360


; The RegisterBlocks.
Vaches_Subsong0DisarkByteRegionStart361
Vaches_Subsong0_RegisterBlock_16
    db 65    ; Initial State: software only.
    db 213    ; Software period.
    db 0    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 212    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 213    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 212    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_16_Loop
    db 85    ; Non-initial State, software only.
    db 213    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 214    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart362
    dw Vaches_Subsong0_RegisterBlock_16_Loop
Vaches_Subsong0DisarkPointerRegionEnd362

Vaches_Subsong0_RegisterBlock_38
    db 65    ; Initial State: software only.
    db 246    ; Software period.
    db 3    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 245    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 246    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 245    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_38_Loop
    db 85    ; Non-initial State, software only.
    db 246    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 247    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart363
    dw Vaches_Subsong0_RegisterBlock_38_Loop
Vaches_Subsong0DisarkPointerRegionEnd363

Vaches_Subsong0_RegisterBlock_39
    db 105    ; Initial State: software only.
    db 160    ; Software period.
    db 0    ; Software period.

    db 53    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 53    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 49    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 45    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 41    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 37    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 17    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 13    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 9    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 5    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_39_Loop
    db 4    ; Non-initial State, no software no hardware.

    db 8    ; Loop to index 105.
Vaches_Subsong0DisarkPointerRegionStart364
    dw Vaches_Subsong0_RegisterBlock_39_Loop
Vaches_Subsong0DisarkPointerRegionEnd364

Vaches_Subsong0_RegisterBlock_77
    db 105    ; Initial State: software only.
    db 80    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart365
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd365
Vaches_Subsong0_RegisterBlock_117
    db 105    ; Initial State: software only.
    db 120    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart366
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd366
Vaches_Subsong0_RegisterBlock_124
    db 65    ; Initial State: software only.
    db 179    ; Software period.
    db 0    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 178    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 179    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 178    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_124_Loop
    db 85    ; Non-initial State, software only.
    db 179    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 180    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart367
    dw Vaches_Subsong0_RegisterBlock_124_Loop
Vaches_Subsong0DisarkPointerRegionEnd367

Vaches_Subsong0_RegisterBlock_125
    db 65    ; Initial State: software only.
    db 28    ; Software period.
    db 1    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 27    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 28    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 27    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_125_Loop
    db 85    ; Non-initial State, software only.
    db 28    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 29    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart368
    dw Vaches_Subsong0_RegisterBlock_125_Loop
Vaches_Subsong0DisarkPointerRegionEnd368

Vaches_Subsong0_RegisterBlock_133
    db 65    ; Initial State: software only.
    db 253    ; Software period.
    db 0    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 252    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 253    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 252    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_133_Loop
    db 85    ; Non-initial State, software only.
    db 253    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 254    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart369
    dw Vaches_Subsong0_RegisterBlock_133_Loop
Vaches_Subsong0DisarkPointerRegionEnd369

Vaches_Subsong0_RegisterBlock_165
    db 65    ; Initial State: software only.
    db 190    ; Software period.
    db 0    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 189    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 190    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 189    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_165_Loop
    db 85    ; Non-initial State, software only.
    db 190    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 191    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart370
    dw Vaches_Subsong0_RegisterBlock_165_Loop
Vaches_Subsong0DisarkPointerRegionEnd370

Vaches_Subsong0_RegisterBlock_166
    db 65    ; Initial State: software only.
    db 239    ; Software period.
    db 0    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 238    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 239    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 238    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_166_Loop
    db 85    ; Non-initial State, software only.
    db 239    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 240    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 16.
Vaches_Subsong0DisarkPointerRegionStart371
    dw Vaches_Subsong0_RegisterBlock_166_Loop
Vaches_Subsong0DisarkPointerRegionEnd371

Vaches_Subsong0_RegisterBlock_167
    db 105    ; Initial State: software only.
    db 60    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart372
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd372
Vaches_Subsong0_RegisterBlock_168
    db 0    ; Initial State: no software, no hardware.

Vaches_Subsong0_RegisterBlock_168_Loop
    db 4    ; Non-initial State, no software no hardware.

    db 8    ; Loop to index 1.
Vaches_Subsong0DisarkPointerRegionStart373
    dw Vaches_Subsong0_RegisterBlock_168_Loop
Vaches_Subsong0DisarkPointerRegionEnd373

Vaches_Subsong0_RegisterBlock_7
    db 65    ; Initial State: software only.
    db 124    ; Software period.
    db 1    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 123    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 124    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 123    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 124    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_7_Loop
    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 125    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 124    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 21.
Vaches_Subsong0DisarkPointerRegionStart374
    dw Vaches_Subsong0_RegisterBlock_7_Loop
Vaches_Subsong0DisarkPointerRegionEnd374

Vaches_Subsong0_RegisterBlock_15
    db 65    ; Initial State: software only.
    db 189    ; Software period.
    db 3    ; Software period.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 33    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 29    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 188    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 189    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 25    ; Non-initial State, software only.

    db 89    ; Non-initial State, software only.
    db 188    ; New LSB for software period.

    db 25    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 189    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_15_Loop
    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 190    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 85    ; Non-initial State, software only.
    db 189    ; New LSB for software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

    db 8    ; Loop to index 21.
Vaches_Subsong0DisarkPointerRegionStart375
    dw Vaches_Subsong0_RegisterBlock_15_Loop
Vaches_Subsong0DisarkPointerRegionEnd375

Vaches_Subsong0_RegisterBlock_53
    db 65    ; Initial State: software only.
    db 190    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart376
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_165 + 3
Vaches_Subsong0DisarkPointerRegionEnd376
Vaches_Subsong0_RegisterBlock_55
    db 65    ; Initial State: software only.
    db 239    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart377
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_166 + 3
Vaches_Subsong0DisarkPointerRegionEnd377
Vaches_Subsong0_RegisterBlock_0
    db 105    ; Initial State: software only.
    db 239    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart378
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd378
Vaches_Subsong0_RegisterBlock_40
    db 105    ; Initial State: software only.
    db 120    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart379
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd379
Vaches_Subsong0_RegisterBlock_78
    db 105    ; Initial State: software only.
    db 213    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart380
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd380
Vaches_Subsong0_RegisterBlock_118
    db 105    ; Initial State: software only.
    db 107    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart381
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd381
Vaches_Subsong0_RegisterBlock_141
    db 73    ; Initial State: software only.
    db 201    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart382
; Optimization: goto common Block at index 29.
    dw Vaches_Subsong0_RegisterBlock_39 + 31
Vaches_Subsong0DisarkPointerRegionEnd382
Vaches_Subsong0_RegisterBlock_143
    db 73    ; Initial State: software only.
    db 28    ; Software period.
    db 1    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart383
; Optimization: goto common Block at index 29.
    dw Vaches_Subsong0_RegisterBlock_39 + 31
Vaches_Subsong0DisarkPointerRegionEnd383
Vaches_Subsong0_RegisterBlock_2
    db 105    ; Initial State: software only.
    db 63    ; Software period.
    db 1    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart384
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd384
Vaches_Subsong0_RegisterBlock_10
    db 105    ; Initial State: software only.
    db 142    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart385
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd385
Vaches_Subsong0_RegisterBlock_13
    db 105    ; Initial State: software only.
    db 190    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart386
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd386
Vaches_Subsong0_RegisterBlock_48
    db 105    ; Initial State: software only.
    db 71    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart387
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd387
Vaches_Subsong0_RegisterBlock_51
    db 105    ; Initial State: software only.
    db 95    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart388
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd388
Vaches_Subsong0_RegisterBlock_80
    db 105    ; Initial State: software only.
    db 28    ; Software period.
    db 1    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart389
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd389
Vaches_Subsong0_RegisterBlock_1
    db 105    ; Initial State: software only.
    db 213    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart390
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd390
Vaches_Subsong0_RegisterBlock_4
    db 105    ; Initial State: software only.
    db 190    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart391
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd391
Vaches_Subsong0_RegisterBlock_11
    db 105    ; Initial State: software only.
    db 160    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart392
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd392
Vaches_Subsong0_RegisterBlock_41
    db 105    ; Initial State: software only.
    db 107    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart393
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd393
Vaches_Subsong0_RegisterBlock_44
    db 105    ; Initial State: software only.
    db 95    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart394
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd394
Vaches_Subsong0_RegisterBlock_49
    db 105    ; Initial State: software only.
    db 80    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart395
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd395
Vaches_Subsong0_RegisterBlock_93
    db 105    ; Initial State: software only.
    db 169    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart396
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd396
Vaches_Subsong0_RegisterBlock_137
    db 105    ; Initial State: software only.
    db 85    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart397
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd397
Vaches_Subsong0_RegisterBlock_36
    db 105    ; Initial State: software only.
    db 226    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart398
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd398
Vaches_Subsong0_RegisterBlock_75
    db 105    ; Initial State: software only.
    db 113    ; Software period.
    db 0    ; Software period.

    db 8
Vaches_Subsong0DisarkPointerRegionStart399
; Optimization: goto common Block at index 1.
    dw Vaches_Subsong0_RegisterBlock_39 + 3
Vaches_Subsong0DisarkPointerRegionEnd399
Vaches_Subsong0_RegisterBlock_6
    db 41    ; Initial State: software only.
    db 126    ; Software period.
    db 2    ; Software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_14
    db 41    ; Initial State: software only.
    db 247    ; Software period.
    db 2    ; Software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_52
    db 41    ; Initial State: software only.
    db 63    ; Software period.
    db 1    ; Software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

Vaches_Subsong0_RegisterBlock_54
    db 41    ; Initial State: software only.
    db 190    ; Software period.
    db 0    ; Software period.

    db 21    ; Non-initial State, software only.

    db 21    ; Non-initial State, software only.

Vaches_Subsong0DisarkByteRegionEnd361
